### PR TITLE
Fix unhandled promise rejection

### LINKED ISSUE #133: Requesting functions hangs fovever if the (request-reply) function fails (UnhandledPromiseRejectionWarning)
If users define a function such as:

```js
module.exports = (x) => {
        if (x === 0) {
                throw new Error('Division by zero');
        }
        return 100 / x;
}
```

deploy it and request it as follows:
```sh
curl http://XXX -H'Content-Type:application/json' -d'0' -H'Accept:text/plain' -v
```

The request will hang forever:
```
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> POST / HTTP/1.1
> Host: XXX
> User-Agent: curl/7.64.1
> Content-Type:application/json
> Accept:text/plain
> Content-Length: 1
>
* upload completely sent off: 1 out of 1 bytes
```

The invoker logs are as follows:

```
RIFF 13426: Ready to process signals
RIFF 13426: New invocation started
RIFF 13426: Promoting request-reply function to streaming function
RIFF 13426: Streaming pipeline initialized
RIFF 13426: Input signal received
RIFF 13426: Start signal with: output content types: text/plain, input names: [in], output names: [out]
RIFF 13426: Wiring 1 input stream(s)
RIFF 13426: Wiring 1 output stream(s)
RIFF 13426: Ready to process data
RIFF 13426: Input signal received
RIFF 13426: Forwarding data for input #0
(node:13426) UnhandledPromiseRejectionWarning: Error
    at MappingTransform._handleError (/Users/fbiville/workspace/node-function-invoker/lib/mapping-transform.js:33:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:13426) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13426) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
RIFF 13426: Ending input streams
```

### PR DESCRIPTION
**Pull request by fbiville**
Fixes #133.

## How to validate

1. create the following function, e.g. `/tmp/joy_division.js`:
```js
module.exports = (x) => {
        if (x === 0) {
                throw new Error('Division by zero');
        }
        return 100 / x;
}
```
or even `/tmp/async_joy_division.js`:
```js
module.exports = async (x) => {
        if (x === 0) {
                throw new Error('Division by zero');
        }
        return 100 / x;
}
```
2. point the node invoker to the PR branch
3. build (`make`) and run the [adapter](https://github.com/projectriff/streaming-http-adapter)
```shell
FUNCTION_URI=/tmp/joy_division.js NODE_DEBUG='riff' ./streaming-http-adapter npm --prefix ~/workspace/node-function-invoker start
```
4. send a failing request
```shell
curl http://localhost:8080 -H'Content-Type:application/json' -d'0' -H'Accept:text/plain' -v
```

The request should not hang and a 500 response should be received.

### CODE REVIEW

File: lib/mapping-transform.js [hunk 1]
```diff
@@ -11,28 +11,22 @@ module.exports = class MappingTransform extends Transform {
     }
 
     _transform(chunk, _, callback) {
+        let value;
```
Comment (scothis) [inline lib/mapping-transform.js]: Life is easier if you pick with a sync or async style and stick with it. Mixing the two is a common source of bugs. 

For example, if `this._function` throws you're emitting an error on the current stream. However, if `this._function` returns a rejected promise, the callback is called with an error. This is wrong. Throwing and returning a rejected promise are semantically identical. The only difference is that one of them happens synchronously and the other async. If something about this distinction as implemented is important, we have bigger latent bugs here.

Considering `this._function` is possibly async and `_transform` cannot be async, sticking with a promise chain is your best bet.

```suggestion
    _transform(chunk, _, callback) {
        Promise.resolve(chunk)
            .then(req => this._function(req))
            .then(res => callback(null, res))
            .catch(err => callback(new RiffError(errorTypes.REQUEST_REPLY_FUNCTION_RUNTIME, err));
    }
```

Comment (fbiville) [reply lib/mapping-transform.js]: It does not seem to work.
Using the adapter and the function described [here](https://github.com/projectriff/node-function-invoker/issues/133#issuecomment-584075817), the request hangs.

Comment (fbiville) [reply lib/mapping-transform.js]: It seems that the request does _not_ hang when using `this.emit('error', error)` in the catch clause of the try-catch block surrounding `this._function`.
I agree this does seem right. 

Not sure why `callback(error)` does not have the same effect, nor `this.emit('error', ...)` in a promise chain.

Comment (fbiville) [reply lib/mapping-transform.js]: I think we need to stick to a synchronous style, else `_transform` will return before the promise chain completes.

Comment (fbiville) [reply lib/mapping-transform.js]: Note that the current PR contents fix the problem with synchronous functions but the same problem still occurs with async functions.

I am not sure we can really reconcile the synchronous nature of streams and the possibly async nature of functions here.

Comment (fbiville) [reply lib/mapping-transform.js]: Thanks to https://github.com/projectriff/node-function-invoker/pull/147, I'm now much more familar with promises than before.
@scothis your initial suggestion works well, the only issue with it is that `callback(someError)` throws in the promise `catch`. Because of that, the promise ends up being rejected and given there is no subsequent `catch`, then the warning appears.

Comment (fbiville) [reply lib/mapping-transform.js]: FYI: I just asked [nodejs/help](https://github.com/nodejs/help/issues/2477) to see what's the best course of action.

Comment (fbiville) [reply lib/mapping-transform.js]: Seems `process.nextTick` is the way to go.

File: lib/mapping-transform.js [hunk 2]
```diff
@@ -5,34 +5,20 @@ const {types: errorTypes} = require('./errors');
...
-            err
-        ));
+        Promise.resolve(chunk)
+            .then(value => this._function(value))
+            .then(
+                result => callback(null, result),
+                err => callback(new RiffError(errorTypes.REQUEST_REPLY_FUNCTION_RUNTIME, err))
+            )
+            // allow promise to run to completion before propagating error
+            .catch(err => process.nextTick(() => {
```
Comment (scothis) [inline lib/mapping-transform.js]: using `process.nextTick()` pushes the error out of the promise chain, so you no longer see that warning, but doesn't do anything meaningful for actually handling the cause of the error.

```suggestion
            .catch(err => {
                if (this.destroyed) {
                    //  the error is unhandleable
                    // TODO log it?
                    return;
                }
                this.destroy(err);
            });
```

**Comment by fbiville** [comment]
Now rebased

File: lib/mapping-transform.js (hunk 2 above)
Comment (fbiville) [reply lib/mapping-transform.js]: With this implementation, the invocation does not stop anymore, so the original problem (`curl` hangs) still occurs.

Comment (fbiville) [reply lib/mapping-transform.js]: (not saying that the initial `(err) => process.nextTick(() => {throw err})` is the way to go as it crashes the entire process)

Comment (scothis) [reply lib/mapping-transform.js]: let's fix the root problem (application error handling/propagation) rather than working around a symptom

Comment (fbiville) [reply lib/mapping-transform.js]: putting this PR on hold, then

**Comment by fbiville** [comment]
Now rebased.

**Comment by fbiville** [comment]
I actually found a simpler way to solve the problem.

Request-reply functions error were handled via `MappingTransform#_handleError`. 
What `_handleError`does is to emit an error on the `MappingTransform` stream.

So far so good. But not enough.

Emitting an error when there are no listeners attached [triggers a throw](https://nodejs.org/api/events.html#events_error_events). And that's the case here: no listeners, hence `_handleError` throws, which leaves the promise in a rejected state. Given there are no further rejection handler, we end up with the warning described in #133.

The real problem is that the error is emitted but it is not intercepted anywhere.

What the solution does now consists in propagating the error back the unmarshaller so that the streaming pipeline can then go as usual, i.e. cancel the invocation.

File: lib/mapping-transform.js [hunk 3]
```diff
@@ -9,26 +9,18 @@ module.exports = class MappingTransform extends Transform {
...
-        try {
-            Promise.resolve(this._function(chunk)).then(
-                this._handleResult(callback),
-                this._handleError.bind(this)
+        Promise.resolve(chunk)
+            .then(this._function)
+            .then(
+                (result) => callback(null, result),
+                (err) =>
+                    this.emit(
```
Comment (scothis) [inline lib/mapping-transform.js]: why bypass the callback?

File: lib/streaming-pipeline.js [hunk 4]
```diff
@@ -226,13 +226,25 @@ module.exports = class StreamingPipeline extends Writable {
...
+                console.error(
+                    `error from ${this._errorOrigin(err)}: ${err.toString()}`
+                );
                 this.emit("error", err);
             });
             this._functionInputs[i] = unmarshaller;
         }
     }
 
+    _errorOrigin(err) {
```
Comment (scothis) [inline lib/streaming-pipeline.js]: is this needed? The error type is already part of the message

Comment (fbiville) [reply lib/streaming-pipeline.js]: it's just to make the error message a little less ambiguous, as the prefix would be otherwise "error from unmarshaller: ..." (technically, the error is indeed intercepted from the unmarshaller, but that's an implementation detail)

File: lib/mapping-transform.js (hunk 3 above)
Comment (fbiville) [reply lib/mapping-transform.js]: No valid reason :) Thanks!

File: lib/mapping-transform.js [hunk 5]
```diff
@@ -9,26 +9,17 @@ module.exports = class MappingTransform extends Transform {
...
-        try {
-            Promise.resolve(this._function(chunk)).then(
-                this._handleResult(callback),
-                this._handleError.bind(this)
+        Promise.resolve(chunk)
+            .then(this._function)
+            .then(
+                (result) => callback(null, result),
+                (err) =>
+                    callback(
```
Comment (scothis) [inline lib/mapping-transform.js]: need to handle cases where the callback throws. For example if the stream has already errors or closed.

I'm not sure there is anything to do with those errors but log and drop, but we should propagate an unhandled promise rejection.

Comment (fbiville) [reply lib/mapping-transform.js]: I was wondering the same. I can at least log the error for sure.

Comment (fbiville) [reply lib/mapping-transform.js]: I think callback would throw if the "downstream" marshaller errors, so that case will be handled by the streaming pipeline anyway. Logging is probably the best recourse.

File: lib/streaming-pipeline.js (hunk 4 above)
Comment (scothis) [reply lib/streaming-pipeline.js]: any ambiguity should be addressed when the errors are created, not when they are logged. Unless there is specific context that can be added when logged, but this isn't doing that.

Comment (fbiville) [reply lib/streaming-pipeline.js]: let's follow up with another PR
